version: "2"

networks:
  test:
    name: fabric_test


services:
  ca-org1:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      # - FABRIC_CA_SERVER_PORT=7054
      # - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:17054